from .components import (
    MapWidget,
    layer,
    scatterplot_layer,
    geojson_layer,
    tile_layer,
    bitmap_layer,
    # Layer helpers (v0.7.0)
    arc_layer,
    icon_layer,
    path_layer,
    line_layer,
    text_layer,
    column_layer,
    polygon_layer,
    heatmap_layer,
    hexagon_layer,
    h3_hexagon_layer,
    # Layer helpers (v0.9.0) — geo-layers & aggregation-layers
    trips_layer,
    great_circle_layer,
    contour_layer,
    grid_layer,
    screen_grid_layer,
    mvt_layer,
    wms_layer,
    point_cloud_layer,
    simple_mesh_layer,
    terrain_layer,
    # Mesh geometry helpers (v1.3.0)
    custom_geometry,
    COORDINATE_SYSTEM,
    CARTO_POSITRON,
    CARTO_DARK,
    CARTO_VOYAGER,
    OSM_LIBERTY,
    # Color-scale utilities
    color_range,
    color_bins,
    color_quantiles,
    depth_color,
    PALETTE_VIRIDIS,
    PALETTE_PLASMA,
    PALETTE_OCEAN,
    PALETTE_THERMAL,
    PALETTE_CHLOROPHYLL,
    # Binary data transport
    encode_binary_attribute,
    # View helpers
    map_view,
    orthographic_view,
    first_person_view,
    globe_view,
    orbit_view,
    # Widget helpers (v0.8.0)
    zoom_widget,
    compass_widget,
    fullscreen_widget,
    scale_widget,
    gimbal_widget,
    reset_view_widget,
    screenshot_widget,
    fps_widget,
    loading_widget,
    timeline_widget,
    geocoder_widget,
    theme_widget,
    # Experimental widget helpers (v9.2+)
    context_menu_widget,
    info_widget,
    splitter_widget,
    stats_widget,
    view_selector_widget,
    # MapLibre control helpers
    geolocate_control,
    globe_control,
    terrain_control,
    # Third-party MapLibre plugin controls
    legend_control,
    opacity_control,
    # Custom deck.gl legend
    deck_legend_control,
    # Transition helper (v0.8.0)
    transition,
    # Control constants (v0.2.0)
    CONTROL_TYPES,
    CONTROL_POSITIONS,
    # Extension helpers (v1.0.0)
    brushing_extension,
    collision_filter_extension,
    data_filter_extension,
    mask_extension,
    clip_extension,
    terrain_extension,
    fill_style_extension,
    path_style_extension,
    fp64_extension,
)
from .extensions import Extension
from .effects import (  # noqa: F401
    ambient_light,
    point_light,
    directional_light,
    sun_light,
    lighting_effect,
    post_process_effect,
)
from .parsers import parse_shyfem_grd, parse_shyfem_mesh  # noqa: F401
from .ui import head_includes
from .ibm import (
    SPECIES_COLORS,
    ICON_ATLAS,
    ICON_MAPPING,
    format_trips,
    trips_animation_ui,
    trips_animation_server,
)
from ._demo_data import (  # noqa: F401
    SHYFEM_VIEW,
    make_h3_data,
    make_point_cloud_data,
    make_shyfem_polygon_data,
    make_shyfem_mesh_data,
)
from ._version import __version__


def __getattr__(name: str):
    """Lazy-load the built-in demo ``app`` to avoid importing the full Shiny
    application framework when users only need components like ``MapWidget``."""
    if name == "app":
        from .app import app  # noqa: F811

        return app
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "app",
    "MapWidget",
    "layer",
    "scatterplot_layer",
    "geojson_layer",
    "tile_layer",
    "bitmap_layer",
    "arc_layer",
    "icon_layer",
    "path_layer",
    "line_layer",
    "text_layer",
    "column_layer",
    "polygon_layer",
    "heatmap_layer",
    "hexagon_layer",
    "h3_hexagon_layer",
    "trips_layer",
    "great_circle_layer",
    "contour_layer",
    "grid_layer",
    "screen_grid_layer",
    "mvt_layer",
    "wms_layer",
    "point_cloud_layer",
    "simple_mesh_layer",
    "terrain_layer",
    "custom_geometry",
    "COORDINATE_SYSTEM",
    "parse_shyfem_grd",
    "parse_shyfem_mesh",
    "head_includes",
    "CARTO_POSITRON",
    "CARTO_DARK",
    "CARTO_VOYAGER",
    "OSM_LIBERTY",
    "color_range",
    "color_bins",
    "color_quantiles",
    "depth_color",
    "PALETTE_VIRIDIS",
    "PALETTE_PLASMA",
    "PALETTE_OCEAN",
    "PALETTE_THERMAL",
    "PALETTE_CHLOROPHYLL",
    "encode_binary_attribute",
    "map_view",
    "orthographic_view",
    "first_person_view",
    "globe_view",
    "orbit_view",
    "zoom_widget",
    "compass_widget",
    "fullscreen_widget",
    "scale_widget",
    "gimbal_widget",
    "reset_view_widget",
    "screenshot_widget",
    "fps_widget",
    "loading_widget",
    "timeline_widget",
    "geocoder_widget",
    "theme_widget",
    "context_menu_widget",
    "info_widget",
    "splitter_widget",
    "stats_widget",
    "view_selector_widget",
    "geolocate_control",
    "globe_control",
    "terrain_control",
    "legend_control",
    "opacity_control",
    "deck_legend_control",
    "transition",
    "CONTROL_TYPES",
    "CONTROL_POSITIONS",
    "Extension",
    "brushing_extension",
    "collision_filter_extension",
    "data_filter_extension",
    "mask_extension",
    "clip_extension",
    "terrain_extension",
    "fill_style_extension",
    "path_style_extension",
    "fp64_extension",
    # Effect helpers
    "ambient_light",
    "point_light",
    "directional_light",
    "sun_light",
    "lighting_effect",
    "post_process_effect",
    # IBM visual assets & helpers
    "SPECIES_COLORS",
    "ICON_ATLAS",
    "ICON_MAPPING",
    "format_trips",
    "trips_animation_ui",
    "trips_animation_server",
    # Demo data factories
    "SHYFEM_VIEW",
    "make_h3_data",
    "make_point_cloud_data",
    "make_shyfem_polygon_data",
    "make_shyfem_mesh_data",
    "__version__",
]
