"""Deck.gl effect helpers — lighting, post-processing, and light sources.

Effects modify the visual appearance of the entire scene.  They are passed
to ``MapWidget.update()`` via the ``effects`` parameter as a list of spec
dicts generated by the helpers in this module.

Usage
-----
::

    from shiny_deckgl.effects import (
        lighting_effect, ambient_light, point_light,
        directional_light, sun_light, post_process_effect,
    )

    effects = [
        lighting_effect(
            ambient_light(intensity=0.8),
            point_light(position=[20.0, 55.0, 80000], intensity=2.0),
            directional_light(direction=[-1, -3, -1], intensity=0.6),
        ),
        post_process_effect("brightnessContrast", brightness=0.1, contrast=0.2),
    ]

    await map_widget.update(session, layers=[...], effects=effects)

The JS client in ``deckgl-init.js`` resolves these spec dicts into real
deck.gl ``LightingEffect`` / ``PostProcessEffect`` instances.
"""

from __future__ import annotations

from typing import Any

__all__ = [
    "ambient_light",
    "point_light",
    "directional_light",
    "sun_light",
    "lighting_effect",
    "post_process_effect",
]


# ---------------------------------------------------------------------------
# Light source helpers
# ---------------------------------------------------------------------------

def ambient_light(
    color: list[int] | tuple[int, ...] = (255, 255, 255),
    intensity: float = 1.0,
) -> dict[str, Any]:
    """Create an ambient-light spec.

    Ambient light illuminates all objects equally regardless of direction.

    Parameters
    ----------
    color
        RGB color of the light (default white).
    intensity
        Brightness multiplier (default 1.0).
    """
    return {"color": list(color), "intensity": intensity}


def point_light(
    position: list[float],
    color: list[int] | tuple[int, ...] = (255, 255, 255),
    intensity: float = 1.0,
    **kwargs: Any,
) -> dict[str, Any]:
    """Create a point-light spec.

    A point light emits from a single position in all directions, like a
    light bulb.

    Parameters
    ----------
    position
        ``[longitude, latitude, altitude_metres]`` of the light source.
    color
        RGB color (default white).
    intensity
        Brightness multiplier (default 1.0).
    **kwargs
        Additional properties (e.g. ``attenuation``).
    """
    return {"color": list(color), "intensity": intensity, "position": list(position), **kwargs}


def directional_light(
    direction: list[float] | tuple[float, ...] = (-1, -3, -1),
    color: list[int] | tuple[int, ...] = (255, 255, 255),
    intensity: float = 1.0,
    _shadow: bool = False,
    **kwargs: Any,
) -> dict[str, Any]:
    """Create a directional-light spec.

    A directional light emits parallel rays from a distant source (like
    the sun).

    Parameters
    ----------
    direction
        ``[x, y, z]`` direction vector the light points towards.
    color
        RGB color (default white).
    intensity
        Brightness multiplier (default 1.0).
    _shadow
        Enable experimental shadow rendering (default ``False``).
        Requires deck.gl shadow support.
    **kwargs
        Additional properties.
    """
    spec: dict[str, Any] = {
        "color": list(color),
        "intensity": intensity,
        "direction": list(direction),
    }
    if _shadow:
        spec["_shadow"] = True
    spec.update(kwargs)
    return spec


def sun_light(
    timestamp: int | float,
    color: list[int] | tuple[int, ...] = (255, 255, 255),
    intensity: float = 1.0,
    _shadow: bool = False,
    **kwargs: Any,
) -> dict[str, Any]:
    """Create a sun-light spec.

    A specialised directional light whose direction is computed from the
    sun's position at a given time.

    Parameters
    ----------
    timestamp
        Unix timestamp in milliseconds (e.g. from
        ``datetime.datetime.now().timestamp() * 1000``).
    color
        RGB color (default white).
    intensity
        Brightness multiplier (default 1.0).
    _shadow
        Enable experimental shadow rendering (default ``False``).
    **kwargs
        Additional properties.
    """
    spec: dict[str, Any] = {
        "@@sunLight": True,
        "timestamp": timestamp,
        "color": list(color),
        "intensity": intensity,
    }
    if _shadow:
        spec["_shadow"] = True
    spec.update(kwargs)
    return spec


# ---------------------------------------------------------------------------
# Effect helpers
# ---------------------------------------------------------------------------

def lighting_effect(
    ambient: dict | None = None,
    *lights: dict,
    **kwargs: Any,
) -> dict[str, Any]:
    """Create a ``LightingEffect`` spec.

    Combines an optional ambient light with any number of point and/or
    directional lights (including sun lights).

    Parameters
    ----------
    ambient
        An ambient-light dict from :func:`ambient_light`, or ``None``.
    *lights
        Any number of point-light, directional-light, or sun-light dicts
        from :func:`point_light`, :func:`directional_light`, or
        :func:`sun_light`.
    **kwargs
        Additional effect properties.

    Returns
    -------
    dict
        A spec dict with ``type="LightingEffect"`` that the JS client
        resolves into a real ``deck.LightingEffect``.

    Examples
    --------
    ::

        lighting_effect(
            ambient_light(intensity=0.5),
            point_light([20, 55, 80000], intensity=2.0),
        )

        lighting_effect(
            ambient_light(),
            directional_light([-1, -3, -1], intensity=0.8, _shadow=True),
            sun_light(timestamp=1700000000000),
        )
    """
    spec: dict[str, Any] = {"type": "LightingEffect"}
    if ambient is not None:
        spec["ambientLight"] = ambient

    # Separate point lights, sun lights, and directional lights
    point_lights: list[dict] = []
    directional_lights: list[dict] = []
    sun_lights: list[dict] = []

    for light in lights:
        if light.get("@@sunLight"):
            sun_lights.append(light)
        elif "position" in light:
            point_lights.append(light)
        elif "direction" in light:
            directional_lights.append(light)

    if point_lights:
        spec["pointLights"] = point_lights
    if directional_lights:
        spec["directionalLights"] = directional_lights
    if sun_lights:
        spec["sunLights"] = sun_lights

    spec.update(kwargs)
    return spec


def post_process_effect(
    shader_module: str,
    **kwargs: Any,
) -> dict[str, Any]:
    """Create a ``PostProcessEffect`` spec.

    Post-process effects apply screen-space pixel manipulation to the
    rendered output (blur, contrast, vignette, etc.).

    Parameters
    ----------
    shader_module
        Name of the luma.gl shader module from ``@luma.gl/effects``.
        Supported modules include:

        - ``"brightnessContrast"`` — adjust brightness and contrast
        - ``"hueSaturation"`` — adjust hue and saturation
        - ``"noise"`` — add noise
        - ``"sepia"`` — sepia tone
        - ``"vibrance"`` — adjust color vibrance
        - ``"vignette"`` — darken edges
        - ``"tiltShift"`` — tilt-shift blur
        - ``"colorHalftone"`` — color halftone dots
        - ``"dotScreen"`` — dot screen pattern
        - ``"edgeWork"`` — edge detection
        - ``"hexagonalPixelate"`` — hexagonal pixelation
        - ``"ink"`` — ink effect
        - ``"magnify"`` — magnifying glass
        - ``"triangleBlur"`` — triangle blur
        - ``"zoomBlur"`` — zoom blur

    **kwargs
        Shader-module-specific parameters (e.g. ``brightness=0.5``).

    Returns
    -------
    dict
        A spec dict with ``type="PostProcessEffect"`` that the JS client
        resolves into a real ``deck.PostProcessEffect``.

    Examples
    --------
    ::

        post_process_effect("brightnessContrast", brightness=0.1, contrast=0.3)
        post_process_effect("vignette", radius=0.5, amount=0.5)
    """
    return {"type": "PostProcessEffect", "shaderModule": shader_module, **kwargs}
